[package]
name = "sample-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.114"
typedb-driver = { version = "3.0.5" }
tokio = "1.43.0"
futures-util = "0.3.31"
