version: 2.1
commands:
  bazel_install:
    steps:
      - run:
          name: Bazel - Install
          command: |
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
            chmod +x bazel-0.20.0-installer-linux-x86_64.sh
            sudo ./bazel-0.20.0-installer-linux-x86_64.sh

  bazel_add_rbe_credential:
    steps:
      - run:
          name: Bazel - Add RBE Credential
          command: |
            if [[ -n "$BAZEL_RBE_CREDENTIAL" ]]; then
              BAZEL_RBE_CREDENTIAL_LOCATION=~/.config/gcloud/application_default_credentials.json
              echo "An RBE credential is found and will be saved to $BAZEL_RBE_CREDENTIAL_LOCATION. Bazel will be executed with RBE support."
              mkdir -p ~/.config/gcloud/
              echo $BAZEL_RBE_CREDENTIAL > "$BAZEL_RBE_CREDENTIAL_LOCATION"
            else
              echo "No RBE credential found. Bazel will be executed locally without RBE support."
            fi

  bazel:
    parameters:
      command:
          type: string
    steps:
      - run:
          name: Bazel - Execute
          command: |
            if [[ -f ~/.config/gcloud/application_default_credentials.json ]]; then
              echo "Bazel will be executed with RBE support. This means the build is remotely executed and the cache will be re-used by subsequent CI jobs."
              CMD="<< parameters.command >> --config=rbe"
            else
              echo "Bazel will be executed locally (without RBE support)."
              CMD="<< parameters.command >>"
            fi
            echo "Executing $CMD"
            $CMD

  start_grakn_server:
    steps:
      - run:
          name: Grakn Server - Start
          command: |
            bazel build @graknlabs_grakn_core//:distribution
            unzip bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all.zip -d bazel-genfiles/dist/
            nohup bazel-genfiles/dist/grakn-core-all/grakn server start


jobs:

  test-snippet-graql:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel test //test/snippet:snippet-graql --test_output=streamed

  test-snippet-java:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel test //test/snippet:snippet-java --test_output=streamed

  test-standalone-java-phone-calls:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - start_grakn_server
      - run: bazel test //test/standalone/java:standalone-java-phone-calls --test_output=streamed

  test-standalone-nodejs-phone-calls:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - start_grakn_server
      - run: bazel test //test/standalone/nodejs:standalone-nodejs-phone-calls --test_output=streamed

  test-standalone-python-phone-calls:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - start_grakn_server
      - run: bazel test //test/standalone/python:standalone-python-phone-calls --test_output=streamed


  test-standalone-social-network:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - start_grakn_server
      - run: bazel test //test/standalone/java:standalone-java-social-network --test_output=streamed
      - run: bazel test //test/standalone/nodejs:standalone-nodejs-social-network --test_output=streamed
      - run: bazel test //test/standalone/python:standalone-python-social-network --test_output=streamed


  release-staging:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy docs to staging by updating the docs submodule in web-dev/development
          command: |
            mkdir docs
            cd docs
            python ../.circleci/deploy-docs.py development

  release-production:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy docs to production by updating the docs submodule in web-dev/master
          command: |
            mkdir docs
            cd docs
            python ../.circleci/deploy-docs.py master
    
workflows:
  docs:
    jobs:
      - test-snippet-graql
      - test-snippet-java
      - test-standalone-java-phone-calls
      - test-standalone-nodejs-phone-calls
      - test-standalone-python-phone-calls
      - test-standalone-social-network
      - release-staging:
          filters:
            branches:
              only: development
          requires:
            - test-snippet-graql
            - test-snippet-java
            - test-standalone-java-phone-calls
            - test-standalone-nodejs-phone-calls
            - test-standalone-python-phone-calls
            - test-standalone-social-network
      - release-production:
          filters:
            branches:
              only: master
          requires:
            - test-snippet-graql
            - test-snippet-java
            - test-standalone-java-phone-calls
            - test-standalone-nodejs-phone-calls
            - test-standalone-python-phone-calls
            - test-standalone-social-network