#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2018 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel:
    steps:
      - run:
          name: Install bazel and RBE credential
          command: |
            # Install bazel
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
            chmod +x bazel-0.20.0-installer-linux-x86_64.sh
            sudo ./bazel-0.20.0-installer-linux-x86_64.sh

            # Install RBE credential
            bazel run @graknlabs_build_tools//ci:install-bazel-rbe-credential

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run:
          command: |
            bazel run @graknlabs_build_tools//ci:run-bazel-rbe << parameters.command >>

  run-grakn-server:
    steps:
      - run:
          name: Grakn Server - Start
          command: |
            bazel build @graknlabs_grakn_core//:assemble-linux-targz
            mkdir dist
            tar -xvzf bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
            nohup ./dist/grakn-core-all-linux/grakn server start

jobs:
  build:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - install-bazel
      - run-bazel-rbe:
          command: bazel build //...

  test-query-graql-lang:
    machine: true
    steps:
      - checkout
      - install-bazel
      - run-bazel-rbe:
          command: bazel test //test/query:graql-lang --test_output=errors

  test-query-graql-java:
    machine: true
    steps:
      - checkout
      - install-bazel
      - run-bazel-rbe:
          command: bazel test //test/query:graql-java --test_output=errors

  test-standalone-java-phone-calls:
    machine: true
    steps:
      - checkout
      - install-bazel
      - run-grakn-server
      - run: bazel test //test/standalone/java:phone-calls --test_output=streamed

  test-standalone-nodejs-phone-calls:
    machine: true
    steps:
      - checkout
      - install-bazel
      - run-grakn-server
      - run: bazel test //test/standalone/nodejs:standalone-nodejs-phone-calls --test_output=streamed

  test-standalone-python-phone-calls:
    machine: true
    steps:
      - checkout
      - install-bazel
      - run-grakn-server
      - run: bazel test //test/standalone/python:standalone-python-phone-calls --test_output=streamed


  test-standalone-social-network:
    machine: true
    steps:
      - checkout
      - install-bazel
      - run-grakn-server
      - run: bazel test //test/standalone/java:social-network --test_output=streamed
      - run: bazel test //test/standalone/nodejs:standalone-nodejs-social-network --test_output=streamed
      - run: bazel test //test/standalone/python:standalone-python-social-network --test_output=streamed


  release-staging:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy docs to staging by updating the docs submodule in web-dev/development
          command: |
            mkdir docs
            cd docs
            python ../.circleci/deploy-docs.py development

  release-production:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy docs to production by updating the docs submodule in web-dev/master
          command: |
            mkdir docs
            cd docs
            python ../.circleci/deploy-docs.py master
    
workflows:
  docs:
    jobs:
      - build
      - test-query-graql-lang
      - test-query-graql-java
      - test-standalone-java-phone-calls
      - test-standalone-nodejs-phone-calls
      - test-standalone-python-phone-calls
      - test-standalone-social-network
      - release-staging:
          filters:
            branches:
              only: development
          requires:
            - build
            - test-query-graql-lang
            - test-query-graql-java
            - test-standalone-java-phone-calls
            - test-standalone-nodejs-phone-calls
            - test-standalone-python-phone-calls
            - test-standalone-social-network
      - release-production:
          filters:
            branches:
              only: master
          requires:
            - build
            - test-query-graql-lang
            - test-query-graql-java
            - test-standalone-java-phone-calls
            - test-standalone-nodejs-phone-calls
            - test-standalone-python-phone-calls
            - test-standalone-social-network